### ISSUE TITLE
userinfo endpoint does not return

### ISSUE THREAD

**Issue by andrewkrug** [mozilla-iam/cis_functions#25]
In some testing I've done this morning trying to figure out why I can not log into the sso-dashboard post CIS integration I found that if attributes are integrated that are empty lists the userinfo endpoint no longer returns valid json to flask_pyoidc.  

These fields specifically were the issue:  (If I set them null everything works again)  Prior they were all empty lists.

  "nicknames": "NULL",
  "PGPFingerprints": "NULL",
  "phoneNumbers": "NULL",
  "SSHFingerprints": "NULL",
  "authoritativeGroups": "NULL"

**Comment by gdestuynder** [comment]
when converting claims from oidc to SAML auth0 also triggers an error regarding `app_metadata` being undefined (error shows it as NULL, code sets it as undefined actually -setting it as NULL in the code also triggers type conversion failures in the web task).
this is due to the CIS rule that cleans up the profile. this probably needs to be set to empty string instead in this case (from within the rule)

Also, empty string/array is valid json AFAIK (albeit NULL is the proper result, but as per above sometimes some software fails to handle it) - see also https://stackoverflow.com/questions/30621802/why-does-json-parse-fail-with-the-empty-string

**Comment by gdestuynder** [comment]
we figured its a problem in oic, the sub-sub-lib of all these things
